version: '3.8'
services:
  postgres:
    image: mysql:8.0
    container_name: database_minimarket
    environment:
      - MYSQL_DATABASE=debuggeandoideas
      - MYSQL_ROOT_PASSWORD=debuggeandoideas1
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint - initdb.d/init.sql